# Generated by Django 2.2.6 on 2019-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('link', models.CharField(blank=True, max_length=30)),
                ('activity', models.CharField(choices=[('eco', 'Economy'), ('med', 'Medecine'), ('ind', 'Industry'), ('inf', 'IT'), ('spa', 'Space')], help_text='Your activity', max_length=3)),
            ],
        ),
    ]
